### ISSUE TITLE
Unable to get punctuation triggers working on 0.10.9+

### ISSUE THREAD

**Issue by kjothen** [onyx-platform/onyx#756] opened 2017-04-27 18:38 UTC
lein new onyx-app onyx-trigger-problem

**project.clj**
https://gist.github.com/kjothen/0784b24a7be91bcaf753fa4793dbfa63

**basic.clj**
https://gist.github.com/kjothen/6ad77ed36739a0904b75929b810c6c56

**onyx.log**
https://gist.github.com/kjothen/eeea73a9c93ab33cdc5abaad77a44b74

**Comment by kjothen** [comment] 2017-04-28 08:40
Under 0.10.0-beta14, the exception is no longer thrown. However, I am still unable to find a reliable means to ensure that a window aggregate is emitted and processed downstream in response to a batch completing. 

For example, if I have 5 segments in my batch, and the punctuation trigger fires on a change in event-type from :new-segment to another (such as :task-iteration or :job-completed), then whilst the emit-fn is called and can build a new extent state, this is not flown/processed downstream. In contrast, if I have a segment trigger whose threshold is set as a factor of the elements in the batch (i.e. 5 in the above example), then the new extent state built from the same emit-fn is flown/processed downstream. Sample gists below, any alternative suggestions will be warmly received :-)

lein new onyx-app onyx-trigger-problem

**basic.clj**
https://gist.github.com/kjothen/cb802c1e97ce023a1fa76dcd48a87039

**basic_test.clj**
https://gist.github.com/kjothen/d01e4913cfd9af5b43bd748ab2ac1ee4

**project.clj**
https://gist.github.com/kjothen/ada8c61e4622a8df79e05789189e16c4

**test output**
https://gist.github.com/kjothen/182896e203534f5d41ebbebb54a0cf17

**Comment by MichaelDrogalis** [comment] 2017-04-29 00:01
cc @lbradstreet

**Comment by lbradstreet** [comment] 2017-04-29 06:31
Thanks for the detailed report. I'll have a look at this tomorrow. Thanks

**Comment by kjothen** [comment] 2017-05-04 17:50
Thanks for the response. Would be cool if you could take a look - I've tried every strategy I can think of to work around it. If there were a :last-segment event-type to signify that the segment is the last in the batch, then that would ought to work I reckon.

**Comment by lbradstreet** [comment] 2017-05-04 17:57
Hi @kjothen, my apologies - I've been really busy. I'll try to get to this one today.

**Comment by lbradstreet** [comment] 2017-05-05 06:03
Thanks, I've reproduced it. It looks like jobs don't currently seal in such a way that they can emit messages to downstream tasks. I'll look into whether there's a reasonable fix.

**Comment by kjothen** [comment] 2017-05-05 07:26
Hi @lbradstreet, thanks for looking into it, I can fully appreciate it's a particular tricky problem to solve. If you'd like me to close this issue (the original issue was fixed) and re-open another to reflect this new behavior then just let me know.

**Comment by lbradstreet** [comment] 2017-05-12 19:31
@kjothen thanks. I'll close this issue and reopen a new one.

**Closed by lbradstreet** 2017-05-12 19:31 UTC
Labels: bug
