### ISSUE TITLE
Completely shutdown cluster may not come back up at same onyx/id

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#416] opened 2015-12-03 10:09 UTC
We've seen this once in the past, but it was fixed. I'm seeing it again with the benchmark suite. A whole new onyx/id is required before things come back up.

**Comment by lbradstreet** [comment] 2015-12-04 18:51
It's also possible that this is a quirk of the benchmark suite ansible scripts.

**Comment by MichaelDrogalis** [comment] 2015-12-07 02:47
I wasn't able to reproduce this without the benchmark. Going to remove the Severe tag. I'll investigate what's happening in the Ansible code.

**Comment by MichaelDrogalis** [comment] 2015-12-07 02:47
Actually - going to close this, as I don't want it to look like this is an open bug against Onyx core.

**Comment by lbradstreet** [comment] 2015-12-07 06:49
Fair enough.

**Comment by MichaelDrogalis** [comment] 2015-12-07 19:58
Root cause of #422.

What's going on is that the time in-between when the follower is stopped and started is too short for the ephemeral znodes in ZooKeeper to timeout and get deleted. When the second round of peers join, they see the ephemeral nodes are still present. 2 of the 3 peers successfully bind to what are now dead peers, and block waiting for a message that's never coming. The third peer can't join because the other two are hogging the resources in the stuck prepare phase. The prepare/abort cycle you're seeing is expected and behaving correctly.

**Comment by MichaelDrogalis** [comment] 2015-12-07 22:20
@lbradstreet Fixed in a53236b37ed1f5b8eecdcb931179804e2817f18e.

**Comment by MichaelDrogalis** [comment] 2015-12-08 01:03
Merged into master, closing.

**Closed by MichaelDrogalis** 2015-12-08 01:03 UTC
Labels: bug, SEVERE
