### ISSUE TITLE
Warn if there are not enough peers to complete the job

### ISSUE THREAD

**Issue by bcambel** [onyx-platform/onyx#452] opened 2015-12-18 12:44 UTC
In a local environment, if you have less peers available than the number of tasks, Onyx behaves like this 
```
server INFO [onyx.log.zookeeper] - Starting ZooKeeper: [127.0.0.1:2188] client connection. If Onyx hangs here it may indicate a difficulty connecting to ZooKeeper.
server INFO [onyx.log.zookeeper] - Stopping ZooKeeper client connection
```
Without any warning or exceptions, system completes processing ( while main thread blocked ) 

It would be nice to have at least a warning indicating the low peer count. 
```
WARN: Seems like you have 5 tasks to complete, whereas the current available peer count is 5.
``` 

It's definitely a rookie mistake that I've made, but I've bet this mistake will be repeated by others as well. 

Note: Thanks @lbradstreet for all the help.

Thanks,
Bahadir

**Comment by lbradstreet** [comment] 2015-12-18 12:46
It's kinda tricky to achieve this from submit-job, because it'd require the submit-job to subscribe to the peer log and actually look at the state of the cluster. Maybe this could be a good case for the dashboard.

**Comment by bcambel** [comment] 2015-12-18 15:16
@gardnervickers suggested the following code
```
(defn n-peers
  "Takes a workflow and catalog, returns the minimum number of peers
   needed to execute this job."
  [catalog workflow]
  (let [task-set (into #{} (apply concat workflow))]
    (reduce
     (fn [sum t]
       (+ sum (or (:onyx/min-peers (find-task catalog t)) 1)))
     0 task-set)))
```

**Comment by gardnervickers** [comment] 2015-12-18 15:22
It could be done inside the the job validation portion of `submit-job` I believe. 
https://github.com/onyx-platform/onyx/blob/0.8.x/src/onyx/api.clj#L144-L149

**Comment by lbradstreet** [comment] 2015-12-18 15:43
Unfortunately it's a bit less of a clear case than that.

It's easy to use the n-peers function to check if we have enough peers on our local instance (we just check the component parameter).

The problem comes when we want to submit a job to a cluster, for the following reasons.
1. You want to retain the ability to submit a job to the cluster, and have it be scheduled when peers become free (e.g. another job finishes).
2. Peers may die or be rescheduled in between the time that you submit the job, and the submit job log entry is read. In this case, you're back to a job waiting for peers.
3. Even without 1 & 2, you would have to read back the entire log in submit-job before validation, so you know what the state of the cluster is before you submit it. Even then, 2. may still occur.

I'm happy to look into ways to make what is going on more transparent. The easiest helpful thing is to have dev mode template jobs check for the correct number of peers and complain. Then the user can adjust the number of peers that is started.

**Comment by MichaelDrogalis** [comment] 2015-12-18 15:49
This behavior is no different than what you would see in Storm, Hadoop, or similar. It's critical to remember that Onyx is a distributed system, designed to support a large number of concurrent jobs and tasks. While we go through a great deal of effort to make local development feel as snappy and uncomplicated as possible, there are elements of its design that make certain features intractable.

An Onyx cluster not having enough resources to complete a job is not exceptional behavior, and does not merit throwing an exception, nor a warning. It uses relatively advanced scheduling algorithms to shift around resources between jobs based on priority for tasks. Disallowing a job to be submitting because of lack of resources would be contrary to what it was designed to do, especially in the case of multi-tenancy under a single `:onyx/id`.

Even more so, because Onyx is architected as a masterless system, there is no way at job submission time to know if the cluster has sufficient resources to handle your job. Even if there was a single point of coordination controlling resource distribution, there would need to be a fully coordinated point in time where the world was "frozen" to ensure that the job would be run. This is wrought with problems of its own, and is in short why you don't see a safety net in the other systems that I mentioned.

It's up to the user to understand what Onyx is and read the documentation about how it functions in a distributed context. Not knowing this information won't take you anywhere good.

I don't think there's anything to fix here aside from trying to point the user to the resource scheduling documentation in more places, and perhaps spinning up the Onyx dashboard to see what resources are available with all the running jobs.

**Comment by MichaelDrogalis** [comment] 2015-12-18 17:47
Closing this as there is no clear way to satisfy the request. We're considering adding a lighter command line dashboard to help visibility, but by and large, the solution is understanding the scheduling model.

**Closed by MichaelDrogalis** 2015-12-18 17:47 UTC
Labels: scheduler
