### ISSUE TITLE
Intermittent failure when distributed across multiple nodes

### ISSUE THREAD

**Issue by prismofeverything** [onyx-platform/onyx#385] opened 2015-11-12 19:27 UTC
I get this stacktrace every once in awhile while running onyx on multiple nodes:

    clojure.core.async/thread-call/fn                async.clj:  434
    onyx.peer.task-lifecycle/launch-aux-threads!/fn       task_lifecycle.clj:  449
    onyx.peer.pipeline-extensions/fn/G  pipeline_extensions.clj:    4
    clojure.core/-cache-protocol-fn         core_deftype.clj:  554
    java.lang.IllegalArgumentException: No implementation of method: :ack-segment of protocol: #'onyx.peer.pipeline-extensions/PipelineInput found for class: onyx.peer.function.Function```

No pattern of what causes it, cannot reproduce reliably, but stacktrace is entirely within onyx code.

**Comment by MichaelDrogalis** [comment] 2015-11-12 19:52
Duplicate of #344. Fix is in progress.

**Comment by MichaelDrogalis** [comment] 2015-11-12 19:53
FYI it occurs when running many jobs where peers switch frequently. We've been a little more focused on streaming which is it's been rare to see until now.

**Closed by MichaelDrogalis** 2015-11-12 19:52 UTC
