### ISSUE TITLE
Provide and API for managing state inside of the peer-group

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx#628] opened 2016-07-22 17:52 UTC
Lifecycles provide state management for each peer. There is currently no API for letting users define a single piece of state for all peers on a JVM/peer-group.

This would be useful for sharing many types of expensive resources.

**Comment by MichaelDrogalis** [comment] 2016-07-22 18:27
Dupe of #624, sorry. I forgot that one was open.

**Closed by MichaelDrogalis** 2016-07-22 18:27 UTC
Labels: feature
