### ISSUE TITLE
[ABS] Make window more usable

### ISSUE THREAD

**Issue by chao787** [onyx-platform/onyx#620] opened 2016-07-08 10:40 UTC
The onyx window is very easy to understand and use.

But the problem is sometimes we may need aggragate the result from window.
which is to say, window another window.

Currently, onxy's window is mainly used for `sync`, not event back to loop.
After get this feature, we can easily optimize superlarge window into small ones and agg them in another node.

And, we can easily generate a pattern from here, we can have a way to support window event back to event flow.

For an illustration, we can use a function send agg like `:trigger/sync-window-event ::send-event-back` instead of `:trigger/sync`.

PS:
For my own usecase, I use side-effect to sync event back to loop. which is dirty and annoying. because the window read the result from function and I miss first channce to send window result back to workflow.

Do you think we need this feature?
If so, I can do some PR for this.

**Comment by lbradstreet** [comment] 2016-07-08 10:55
Hi @chao787,

Yes, we absolutely need a way to send results on to other tasks. Unfortunately this is quite hard to do safely with our current fault tolerance mechanisms (issue is here: https://github.com/onyx-platform/onyx/issues/323)

Our next major release will support this behaviour - it is a high priority for us.

**Comment by MichaelDrogalis** [comment] 2016-07-08 15:24
Technically a duplicate of #323, but I'll keep it open so that we can keep the discussion going. Certainly agreed, we need it ASAP, and are actively working on it.

**Comment by drewverlee** [comment] 2017-03-11 01:39
Unless i'm mis interpreting  @chao787's request is part of the ABS release. If so, should this be closed?

**Comment by lbradstreet** [comment] 2017-03-11 01:56
Thanks. Yes this should be closed.

**Closed by lbradstreet** 2017-03-11 01:56 UTC
Labels: ABS, enhancement, feature

**Comment by chao787** [comment] 2017-03-15 06:23
Got the `:trigger/emit` method. Thanks bro
