### ISSUE TITLE
Define peer restart logic on failed lifecycle calls

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#268] opened 2015-08-10 13:55 UTC
Through the use of flow conditions, or exception handling within functions, it's possible to have long running jobs even if function calls fail.

When lifecycle calls fail, the peer will be restarted, however in the case of bad lifecycle functions, this could lead to peers being repeatedly restart. This is probably the desired behaviour - maybe the failure is transitory.

There may be a better approach. For example, limit the number of retries (with exponential back off) and then kill the job if no success is hit within that time.

**Comment by lbradstreet** [comment] 2015-08-10 13:57
cc/@MichaelDrogalis this isn't urgent but it is probably something we should think about and document. I think the current behaviour is OK for the time being.

**Comment by MichaelDrogalis** [comment] 2015-08-10 14:32
Cool, something more expressive here would be good. Maybe along the lines of what Docker allows in this territory.

**Comment by MichaelDrogalis** [comment] 2015-12-12 02:54
Duplicate of #315, closing.

**Closed by MichaelDrogalis** 2015-12-12 02:54 UTC
Labels: feature
