### ISSUE TITLE
Improve error message on entry typos/missing keys

### ISSUE THREAD

**Issue by neverfox** [onyx-platform/onyx#611] opened 2016-07-04 19:00 UTC
Currently, if you make a mistake (typo, missing parameter key etc.) in a catalog/lifecycle/window entry, you get the error `clojure.lang.ExceptionInfo: Argument must be a UUID or string UUID. Type was null` which doesn't tell you much about the problem and the stack trace has no relevant source context so you have to hunt it down. It's fair that this sort of thing could be caught by more judicious use of schemas by the dev, but I thought you should be aware.

**Comment by neverfox** [comment] 2016-07-05 01:20
Ok this is probably a false alarm. It turns out that this error is accompanied by onyx validation error reports that are just further back in the logs from the stack trace and we were missing it in the chaos.

**Comment by MichaelDrogalis** [comment] 2016-07-05 01:29
These errors should also be reported on standard out via pretty printed errors. Can you please submit a reproducer?

**Comment by MichaelDrogalis** [comment] 2016-07-06 16:46
Closing, couldnt reproduce on my end.

**Closed by MichaelDrogalis** 2016-07-06 16:46 UTC
